### ISSUE TITLE
CALICO_DISABLE_FILE_LOGGING leads to runsv spamming the log

### ISSUE THREAD

**Issue by wrouesnel** [projectcalico/calico-containers#1000]
```
runsv bird6: fatal: unable to start log/./run: file does not exist
runsv confd: fatal: unable to start log/./run: file does not exist
runsv felix: fatal: unable to start log/./run: file does not exist
```
It looks like `rm -r` fails to remove the directory when the container starts up.

**Comment by tomdee** [comment]
This is fixed in the latest code. Closing

**Comment by klynch** [comment]
@tomdee I'm still seeing this using `quay.io/calico/node:v1.0.0-beta` deployed as a DaemonSet.
